project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "notes/*.qmd"

website:
  title: "gs3393"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: work.qmd
        text: Work
      - href: notes.qmd
        text: Notes
    right:
      - icon: github
        href: https://github.com/gs3393

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
