<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-22">
<meta name="description" content="DirectEdit’s background-preservation score on PIE-Bench cannot isolate its inversion contribution, because the method pastes the source latent back outside the edit mask. A code reading, the paper’s own no-mask row, and a four-condition measurement show where the number comes from and what a table would need in order to separate the two.">

<title>What Background Preservation Actually Measures in Image-Editing Benchmarks – gs3393</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/site/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0466e08c6a400aced7fa0d3d15dffa7d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-9b36bde479e88d7d845adaafafc129ba.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0466e08c6a400aced7fa0d3d15dffa7d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f931eb4ea337525074ba78c800d26bd1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-f7157752fec76fb827e72675ee800a39.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-f931eb4ea337525074ba78c800d26bd1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<meta property="og:title" content="What Background Preservation Actually Measures in Image-Editing Benchmarks – gs3393">
<meta property="og:description" content="DirectEdit’s background-preservation score on PIE-Bench cannot isolate its inversion contribution, because the method pastes the source latent back outside the edit mask. A code reading, the paper’s own no-mask row, and a four-condition measurement show where the number comes from and what a table would need in order to separate the two.">
<meta property="og:image" content="https://gs3393.github.io/assets/site/social-card.png">
<meta property="og:site_name" content="gs3393">
<meta property="og:image:height" content="630">
<meta property="og:image:width" content="1200">
<meta name="twitter:title" content="What Background Preservation Actually Measures in Image-Editing Benchmarks – gs3393">
<meta name="twitter:description" content="DirectEdit’s background-preservation score on PIE-Bench cannot isolate its inversion contribution, because the method pastes the source latent back outside the edit mask. A code reading, the paper’s own no-mask row, and a four-condition measurement show where the number comes from and what a table would need in order to separate the two.">
<meta name="twitter:image" content="https://gs3393.github.io/assets/site/social-card.png">
<meta name="twitter:image-height" content="630">
<meta name="twitter:image-width" content="1200">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">gs3393</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notes.html"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/gs3393"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#the-metric-everyone-reports" id="toc-the-metric-everyone-reports" class="nav-link active" data-scroll-target="#the-metric-everyone-reports">The metric everyone reports</a></li>
  <li><a href="#a-number-worth-looking-at" id="toc-a-number-worth-looking-at" class="nav-link" data-scroll-target="#a-number-worth-looking-at">A number worth looking at</a></li>
  <li><a href="#what-the-blending-step-actually-does" id="toc-what-the-blending-step-actually-does" class="nav-link" data-scroll-target="#what-the-blending-step-actually-does">What the blending step actually does</a></li>
  <li><a href="#so-there-is-a-reference-point" id="toc-so-there-is-a-reference-point" class="nav-link" data-scroll-target="#so-there-is-a-reference-point">So there is a reference point</a></li>
  <li><a href="#measuring-it" id="toc-measuring-it" class="nav-link" data-scroll-target="#measuring-it">Measuring it</a></li>
  <li><a href="#so-what-should-be-reported" id="toc-so-what-should-be-reported" class="nav-link" data-scroll-target="#so-what-should-be-reported">So what should be reported</a></li>
  <li><a href="#limits-of-what-i-checked" id="toc-limits-of-what-i-checked" class="nav-link" data-scroll-target="#limits-of-what-i-checked">Limits of what I checked</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<p class="post-kicker" data-type="Experiment"><a href="../notes.html">Experiment</a></p>
<h1 class="title">What Background Preservation Actually Measures in Image-Editing Benchmarks</h1>
<p class="subtitle lead">Reading DirectEdit’s PIE-Bench numbers, with a 151-image check on SD3.5-medium</p>
</div>

<div>
  <div class="description">
    DirectEdit’s background-preservation score on PIE-Bench cannot isolate its inversion contribution, because the method pastes the source latent back outside the edit mask. A code reading, the paper’s own no-mask row, and a four-condition measurement show where the number comes from and what a table would need in order to separate the two.
  </div>
</div>

<div class="post-meta">
  <span class="date">September 22, 2026</span>
  <ul class="post-topics" aria-label="Topics">
      <li class="topic">Editing</li>
      <li class="topic">Evaluation</li>
    </ul>
</div>


</header>


<blockquote class="blockquote">
<p>DirectEdit reports a +10.67 dB jump in background PSNR on PIE-Bench. Its released code pastes the source latent back outside an edit mask at every step, so that column cannot separate paste quality from inversion quality. This note traces the mechanism, uses the paper’s own no-mask row, and measures four conditions on SD3.5-medium to show what the score does and does not say.</p>
</blockquote>
<p>Paper: Desong Yang and Mang Ye, <em>DirectEdit: Step-Level Accurate Inversion for Flow-Based Image Editing</em>, ICML 2026 — <a href="https://arxiv.org/abs/2605.02417">arXiv:2605.02417</a>, <a href="https://github.com/Tr1stesse/DirectEdit">code</a>. Benchmark: Ju et al., <em>PnPInversion</em> / PIE-Bench — <a href="https://arxiv.org/abs/2310.01506">arXiv:2310.01506</a>.</p>
<section id="the-metric-everyone-reports" class="level2">
<h2 class="anchored" data-anchor-id="the-metric-everyone-reports">The metric everyone reports</h2>
<p>Text-driven image editing asks a generative model to change one thing and leave everything else alone. Turn the cat into a tiger; keep the wallpaper, the floor, the window frame.</p>
<p>That second half is genuinely hard. A diffusion or flow model regenerates the whole image, so the parts you never mentioned drift anyway. This is why <em>background preservation</em> became a headline metric. PIE-Bench, the benchmark almost every recent editing paper reports on, ships 700 images with mask annotations marking the region that is supposed to change. It then measures PSNR, LPIPS, MSE and SSIM between the source and the edit over the region outside that mask — the part that should have stayed put. (The exact averaging convention has a wrinkle I come back to at the end.)</p>
<p>There is a natural way to read that column. A method with a more faithful inversion drifts less, so its background stays closer to the original, so its PSNR is higher. When a paper titled <em>Step-Level Accurate Inversion</em> posts its largest gain on that column, the reader connects the two. The paper itself is more careful than that — its Figure 1 attributes background preservation to the alignment <em>and</em> a separate feature-interaction mechanism — but the connection is easy to make and, I will argue, wrong for this column.</p>
<p>I want to show why the background number of this method cannot be read as isolating its inversion contribution, what it does tell you instead, and what a table would need to contain for the isolation to be possible.</p>
</section>
<section id="a-number-worth-looking-at" class="level2">
<h2 class="anchored" data-anchor-id="a-number-worth-looking-at">A number worth looking at</h2>
<p>DirectEdit (ICML 2026) reports a large jump on exactly this column. On FLUX.1-dev, background PSNR goes from FlowEdit’s 21.96 dB to <strong>32.63 dB</strong>. In a field where papers fight over tenths of a decibel, +10.67 dB is not an increment.</p>
<p>The paper’s stated contribution is step-level inversion alignment: record the per-step residual of the inversion trajectory, then add it back during the forward pass so the editing branch is always evaluated on latents that match the inversion. No extra network evaluations. It is a neat idea.</p>
<p>But alignment is not the only moving part. The paper ablates four: the alignment, attention feature injection, a mask-guided noise blending step, and the shape of the mask. The third one is where I want to look, and here the authors deserve credit, because they report what it is worth. Table 1 of the paper carries a row labelled <code>Ours (w/o mask)</code>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>FLUX.1-dev</th>
<th>Structure ↓</th>
<th>bg-PSNR ↑</th>
<th>bg-LPIPS ↓</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FlowEdit</td>
<td>27.83</td>
<td>21.96</td>
<td>112.15</td>
</tr>
<tr class="even">
<td>DirectEdit, no mask</td>
<td>21.93</td>
<td>24.70</td>
<td>102.92</td>
</tr>
<tr class="odd">
<td>DirectEdit, full</td>
<td>17.94</td>
<td><strong>32.63</strong></td>
<td>35.45</td>
</tr>
</tbody>
</table>
<p>Turning the mask on, with everything else in place, moves background PSNR by 7.93 dB. The configuration without it beats FlowEdit by 2.74 dB. Those are two effects measured inside one system, not two independent contributions — I come back to that — but they already say the mask is not a footnote.</p>
<p>On SD3.5-medium the pattern is sharper. Without the mask, DirectEdit’s background PSNR is 26.18 — <em>below</em> DNAEdit’s 27.71, one of the baselines it outranks in the headline table. The full configuration reaches 31.82 and takes the top average rank; the no-mask configuration drops from rank 2.43 to 4.29.</p>
<p>None of this is hidden. It is printed in the paper. The question I want to ask is not about this paper’s honesty. It is about what the column can and cannot tell you once the source image is being pasted back into the result.</p>
</section>
<section id="what-the-blending-step-actually-does" class="level2">
<h2 class="anchored" data-anchor-id="what-the-blending-step-actually-does">What the blending step actually does</h2>
<p>Reading <a href="https://github.com/Tr1stesse/DirectEdit">the released code</a> makes the mechanism concrete. Two lines matter, both inside the editing loop.</p>
<p>First, the source branch is not integrated forward. It is overwritten, every step, with the recorded inversion latent:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>prev_sample_src <span class="op">=</span> gt_source_latent</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Second, the blend uses that overwritten source branch as the background:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>prev_sample_tar <span class="op">=</span> prev_sample_tar <span class="op">*</span> latent_mask <span class="op">+</span> prev_sample_src <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> latent_mask)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The paper specifies the same blend. Algorithm 1 writes it against the source branch — <code>Z_tar ← Z_src ⊙ (1−M) + Z_tar ⊙ M</code> — and the first line above is what makes that <code>Z_src</code> the recorded inversion latent rather than a forward-integrated one.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>Follow the last iteration. The recorded inversion latent at the clean end of the trajectory is, by construction, the VAE encoding of the source image. So outside the mask, the final <em>latent</em> is not close to the source — it is the source latent. After decoding, the background pixels are a VAE round-trip of the source wherever the decoder’s receptive field does not reach an edited cell; near the mask boundary the decoder mixes the two.</p>
<p>Whatever the inversion did, whatever the residual re-injection contributed, none of it reaches the background latent. It was overwritten. That is the sentence the rest of this note rests on: for this method, the background column is measuring how well the source was pasted back, and cannot separate that from how well the trajectory was inverted.</p>
</section>
<section id="so-there-is-a-reference-point" class="level2">
<h2 class="anchored" data-anchor-id="so-there-is-a-reference-point">So there is a reference point</h2>
<p>If the background latent is the source latent, the natural comparison is an image that was never edited at all: encode the source, decode it, score it with the same script. I will call that the <em>no-edit reference</em>. It is not a proven upper bound — the decoder is not local, and the code dilates the mask and downsamples it to latent resolution before blending, so pixels near the edit can land on either side of the reference — but it is the right number to put next to a masked method’s score, and in the run below nothing exceeded it on any metric.</p>
<p>The paper reports something adjacent in a different table: whole-image VAE reconstruction on PIE-Bench is 34.38 dB. That is a different measurement scope from the background column, so I re-measure the reference under the benchmark’s own background convention below and get a different number.</p>
<p>The reference is not reached by anything that happens to use a mask. It needs the thing being pasted to be the actual source, which here is what the first code line above buys. The paper’s own ablation shows the failure mode: with plain Euler inversion and no stepwise correction, the mask is still applied, but the reference pasted into the background is a drifted reconstruction, and background PSNR collapses to 16.66 dB. So the components interact — the mask’s effect depends on what it is given to paste.</p>
</section>
<section id="measuring-it" class="level2">
<h2 class="anchored" data-anchor-id="measuring-it">Measuring it</h2>
<p>A derivation from source code is not a result, so I ran it. SD3.5-medium, 512², 30 steps, the repository’s own hyperparameters and its unmodified evaluation script, on a 151-image subset of PIE-Bench stratified across all ten edit types. Four conditions, ~1.2 GPU-hours:</p>
<ul>
<li><strong>no mask</strong> — blending disabled.</li>
<li><strong>auto mask</strong> — SAM2 prompted with a bounding box derived from the ground-truth mask, using the benchmark’s category label to decide whether the box marks the object or the background. This is <em>not</em> the paper’s mask path, which uses an MLLM to find the box; without an API key I gave SAM2 the right location and let it produce an approximate shape. Median IoU with the annotation is 0.94, so read this as “a good mask with imperfect edges,” not as a test of automatic mask finding.</li>
<li><strong>GT mask</strong> — the benchmark’s own annotation, fed through the same dilation and downsampling the code applies to any mask.</li>
<li><strong>no-edit reference</strong> — the source image encoded and decoded, <em>no editing at all</em>, scored by the same script.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th>Structure ↓</th>
<th>bg-PSNR ↑</th>
<th>bg-LPIPS ↓</th>
<th>bg-SSIM ↑</th>
<th>CLIP-edit ↑</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>no mask</td>
<td>17.22</td>
<td>26.13</td>
<td>68.24</td>
<td>88.84</td>
<td>22.53</td>
</tr>
<tr class="even">
<td>auto mask</td>
<td>8.76</td>
<td>33.94</td>
<td>13.58</td>
<td>94.25</td>
<td>22.24</td>
</tr>
<tr class="odd">
<td>GT mask</td>
<td>8.73</td>
<td>35.01</td>
<td>10.16</td>
<td>94.70</td>
<td>22.39</td>
</tr>
<tr class="even">
<td><strong>no-edit reference</strong></td>
<td><strong>0.55</strong></td>
<td><strong>35.77</strong></td>
<td><strong>9.28</strong></td>
<td><strong>94.94</strong></td>
<td>20.23</td>
</tr>
</tbody>
</table>
<p>Background columns are averaged over the 120 images whose annotation leaves a background; the other 31 (style changes, mostly) have no unedited region to score. Structure and CLIP use all 151.</p>
<p>The no-mask row tracks the paper’s <code>Ours (w/o mask)</code> SD3.5 numbers closely: background PSNR 26.13 against 26.18, SSIM 88.84 against 88.75, and both CLIP scores within 0.06. LPIPS and MSE land within one point. Structure Distance is the outlier at 17.22 against 15.23, which I put down to the 151-image subset. That agreement is my positive control: the one configuration for which the paper publishes a number on this setup, reproduced end to end. It does not certify the paper’s numbers, and it says nothing about whether my masks match theirs — but it makes a broken setup an unlikely explanation for the other three rows.</p>
<p>Read the table as distance to the bottom row — the score of not editing — on each metric’s own scale:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>no mask → GT mask → no-edit reference</th>
<th>fraction of the gap closed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>bg-PSNR</td>
<td>26.13 → 35.01 → 35.77</td>
<td><strong>92%</strong></td>
</tr>
<tr class="even">
<td>bg-LPIPS</td>
<td>68.24 → 10.16 → 9.28</td>
<td><strong>99%</strong></td>
</tr>
<tr class="odd">
<td>bg-MSE</td>
<td>33.82 → 5.49 → 5.10</td>
<td><strong>99%</strong></td>
</tr>
<tr class="even">
<td>bg-SSIM</td>
<td>88.84 → 94.70 → 94.94</td>
<td><strong>96%</strong></td>
</tr>
<tr class="odd">
<td>Structure Distance</td>
<td>17.22 → 8.73 → 0.55</td>
<td>51%</td>
</tr>
</tbody>
</table>
<p>Turning on the mask closes 92–99% of the distance from the no-mask row to the no-edit reference on each of the four background columns. That is a statement about the gap, not about proximity in absolute terms: on LPIPS the GT-mask row still sits 9.5% above the reference value, on MSE 7.6%, on PSNR 0.76 dB below. In the edited region CLIP drops by 0.14. The bottom row gives that number some scale — 0.14 is about six percent of the 2.3-point CLIP gap between the no-mask row and not editing — but a CLIP-score ratio is not an editing-success rate, and the no-edit value is a reference rather than a floor, since a wrong edit could score below it. The SAM2 masks — right location, approximate shape — close 81–93% of the same four gaps.</p>
<p>The same tendency appears in every category that has a background to score. Per-category background PSNR under the GT mask lands within 1.6 dB of the reference for all nine, and within 0.5 dB for four of them; for pose changes the two are 32.41 and 32.46.</p>
<p>Structure Distance closes about half the gap. It is computed over the whole image, edited region included, so pasting the background back cannot carry it all the way on its own. I did not run other methods under equalized masks, so I cannot say whether the range that remains on any of these columns is enough to separate methods; what I can say is that on the four background columns that range is small — 0.76 dB of PSNR between the GT-mask row and not editing — and that whatever lives inside it is the geometry of the paste as much as the quality of the edit.</p>
</section>
<section id="so-what-should-be-reported" class="level2">
<h2 class="anchored" data-anchor-id="so-what-should-be-reported">So what should be reported</h2>
<p>I do not think the conclusion is that mask blending is cheating. Masks are a legitimate tool. DirectEdit’s default mask path takes only the image and the two prompts, finds a box with an MLLM and a shape with SAM, so as a <em>system</em> it has the same inputs as FlowEdit and the comparison in Table 1 is a fair comparison of systems.</p>
<p>The problem is what happens next: the background column of that system comparison gets read as evidence about the inversion algorithm. It cannot carry that weight, because for this method the background is the source pasted back. Two different questions need two different tables.</p>
<ol type="1">
<li><strong>“Is this the best editing system for image-plus-text input?”</strong> Compare full systems, mask path included, on all columns. Table 1 does this. Its background columns are scored outside the <em>benchmark’s</em> mask, not the system’s, so for a masked system they fold together several things at once: how much of the background was refilled with the source latent, how well the system’s mask agreed with the annotation, and what the dilation, downsampling and decoding did at the seam. That is a legitimate system-level number. It is not a number about inversion.</li>
<li><strong>“How much does the inversion algorithm contribute?”</strong> Hold the mask condition fixed across methods — the same mask, or no mask — and compare again. Only then does a background difference say something about inversion. Today the only row of this kind is DirectEdit’s own <code>w/o mask</code> line. Its 2.74 dB over FlowEdit is what remains of the <em>system</em> difference once blending is off; attention injection and the rest are still in it, so it is not the alignment’s contribution either. The closest thing the paper offers to that is its own ablation, where swapping the alignment for stepwise correction inside the full configuration costs 1.51 dB of background PSNR and 11.3 points of Structure Distance. Neither number is 10.67.</li>
</ol>
<p>Two small additions make either table easier to read honestly. <strong>Report the no-edit reference as a row</strong> — one VAE round-trip shows the reader where not editing lands on each column. And <strong>report where the mask came from and how much of the image it covers</strong> — annotation, segmentation model, MLLM box — because in the run above, with the editing method held fixed, the mask condition alone moved background PSNR by nearly 9 dB.</p>
<p>The average-rank column deserves its own look. Four of PIE-Bench’s seven metrics sit on one axis, background preservation, and the table above shows those four move together once the source is pasted back. The question is not whether the rank is invalid but how much that four-to-one weighting drives it — and the paper’s Table 1 contains enough to check, because it prints all seven columns for all fifteen rows. Re-ranking those rows as the paper does reproduces its average-rank column to within 0.14 (a tie in CLIP-whole). Collapsing the four background columns into one axis and averaging four ways instead of seven keeps DirectEdit-SD3.5 in first place, but moves the rest of the table: DirectEdit-FLUX falls from second to fifth, FlowEdit-SD3.5 rises from sixth to third, and the gap between DirectEdit-SD3.5 and its own no-mask variant narrows from about 1.9 rank points to 1.0. The weighting does not decide the winner here; it does decide most of what comes after.</p>
<p>The background column of a masked method is, to a first approximation, a paste-quality score. Reading an inversion contribution out of it needs at least the row without the paste, and really needs an ablation that holds everything else fixed. DirectEdit, to its credit, publishes both.</p>
</section>
<section id="limits-of-what-i-checked" class="level2">
<h2 class="anchored" data-anchor-id="limits-of-what-i-checked">Limits of what I checked</h2>
<ul>
<li>SD3.5-medium only, 151 of 700 images, one seed. The FLUX numbers quoted above are the paper’s, not mine.</li>
<li>I did not compare methods under equalized masks. Everything above concerns one method under four conditions; claims about whether the remaining range separates methods would need that second experiment.</li>
<li>A small bookkeeping note: I count ten edit categories because the benchmark’s annotation file has ten (ids 0–9). The DirectEdit paper describes nine.</li>
<li>My auto masks are better than a real automatic pipeline would produce, since the box came from the annotation. They do score higher (33.94) than the paper’s full configuration (31.82), but I cannot read that as evidence about mask quality: the subsets differ, and my GT-mask run scores higher still (35.01).</li>
<li>I did not re-measure what residual re-injection contributes on its own. The paper’s FLUX ablation reports it: with the mask held on, swapping the alignment for the paper’s simpler stepwise correction costs 1.51 dB of background PSNR and 11.3 points of Structure Distance. Those are conditional effects inside the full configuration, not independent contributions; the same appendix’s Euler+attention+mask row (16.66 dB) already shows the components interact.</li>
<li>One quirk I checked and set aside: PIE-Bench’s <code>psnr_unedit_part</code> zeroes the edit region in both images and then takes PSNR over the <em>whole</em> frame, so error-free pixels enter the denominator and inflate the value with mask area. Measured across my four conditions the inflation is a constant 2.13 dB, so it shifts all rows equally and does not affect any comparison above.</li>
</ul>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The appendix’s Algorithm 2, a variant that drops the explicit reconstruction pass, writes the blend against <code>Z_inv</code> directly.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/gs3393\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 gs3393</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://github.com/gs3393">
<p>GitHub</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>