<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-28">
<meta name="description" content="A follow-up to the background-preservation note: FTEdit, FlowEdit, FlowAlign, DNAEdit and DirectEdit on 151 PIE-Bench images with SD3.5-medium, scored with no mask, with the ground-truth mask pasted back at every step, and with pixel compositing. Background columns compress into a narrow band, some differences remain, the average rank moves with the condition, and FlowAlign’s row in the paper looks like an output-normalization effect.">

<title>Give Every Method the Same Mask – gs3393</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/site/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0466e08c6a400aced7fa0d3d15dffa7d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-9b36bde479e88d7d845adaafafc129ba.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0466e08c6a400aced7fa0d3d15dffa7d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f931eb4ea337525074ba78c800d26bd1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-f7157752fec76fb827e72675ee800a39.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-f931eb4ea337525074ba78c800d26bd1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<meta property="og:title" content="Give Every Method the Same Mask – gs3393">
<meta property="og:description" content="A follow-up to the background-preservation note: FTEdit, FlowEdit, FlowAlign, DNAEdit and DirectEdit on 151 PIE-Bench images with SD3.5-medium, scored with no mask, with the ground-truth mask pasted back at every step, and with pixel compositing. Background columns compress into a narrow band, some differences remain, the average rank moves with the condition, and FlowAlign’s row in the paper looks like an output-normalization effect.">
<meta property="og:image" content="https://gs3393.github.io/assets/site/social-card.png">
<meta property="og:site_name" content="gs3393">
<meta property="og:image:height" content="630">
<meta property="og:image:width" content="1200">
<meta name="twitter:title" content="Give Every Method the Same Mask – gs3393">
<meta name="twitter:description" content="A follow-up to the background-preservation note: FTEdit, FlowEdit, FlowAlign, DNAEdit and DirectEdit on 151 PIE-Bench images with SD3.5-medium, scored with no mask, with the ground-truth mask pasted back at every step, and with pixel compositing. Background columns compress into a narrow band, some differences remain, the average rank moves with the condition, and FlowAlign’s row in the paper looks like an output-normalization effect.">
<meta name="twitter:image" content="https://gs3393.github.io/assets/site/social-card.png">
<meta name="twitter:image-height" content="630">
<meta name="twitter:image-width" content="1200">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">gs3393</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notes.html"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/gs3393"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#where-the-last-note-stopped" id="toc-where-the-last-note-stopped" class="nav-link active" data-scroll-target="#where-the-last-note-stopped">Where the last note stopped</a></li>
  <li><a href="#what-the-same-mask-means-for-five-different-methods" id="toc-what-the-same-mask-means-for-five-different-methods" class="nav-link" data-scroll-target="#what-the-same-mask-means-for-five-different-methods">What “the same mask” means for five different methods</a></li>
  <li><a href="#three-conditions-five-methods" id="toc-three-conditions-five-methods" class="nav-link" data-scroll-target="#three-conditions-five-methods">Three conditions, five methods</a></li>
  <li><a href="#what-compresses-and-what-does-not" id="toc-what-compresses-and-what-does-not" class="nav-link" data-scroll-target="#what-compresses-and-what-does-not">What compresses, and what does not</a></li>
  <li><a href="#the-ranking-depends-on-which-table-you-read" id="toc-the-ranking-depends-on-which-table-you-read" class="nav-link" data-scroll-target="#the-ranking-depends-on-which-table-you-read">The ranking depends on which table you read</a></li>
  <li><a href="#what-the-alignment-buys-as-far-as-this-table-can-say" id="toc-what-the-alignment-buys-as-far-as-this-table-can-say" class="nav-link" data-scroll-target="#what-the-alignment-buys-as-far-as-this-table-can-say">What the alignment buys, as far as this table can say</a></li>
  <li><a href="#one-baseline-row-that-does-not-look-like-the-method" id="toc-one-baseline-row-that-does-not-look-like-the-method" class="nav-link" data-scroll-target="#one-baseline-row-that-does-not-look-like-the-method">One baseline row that does not look like the method</a></li>
  <li><a href="#how-to-read-a-table-like-this" id="toc-how-to-read-a-table-like-this" class="nav-link" data-scroll-target="#how-to-read-a-table-like-this">How to read a table like this</a></li>
  <li><a href="#limits" id="toc-limits" class="nav-link" data-scroll-target="#limits">Limits</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<p class="post-kicker" data-type="Experiment"><a href="../notes.html">Experiment</a></p>
<h1 class="title">Give Every Method the Same Mask</h1>
<p class="subtitle lead">Five editing methods on PIE-Bench with the mask condition held fixed, and one baseline row that turned out to depend on a save path</p>
</div>

<div>
  <div class="description">
    A follow-up to the background-preservation note: FTEdit, FlowEdit, FlowAlign, DNAEdit and DirectEdit on 151 PIE-Bench images with SD3.5-medium, scored with no mask, with the ground-truth mask pasted back at every step, and with pixel compositing. Background columns compress into a narrow band, some differences remain, the average rank moves with the condition, and FlowAlign’s row in the paper looks like an output-normalization effect.
  </div>
</div>

<div class="post-meta">
  <span class="date">September 28, 2026</span>
  <ul class="post-topics" aria-label="Topics">
      <li class="topic">Editing</li>
      <li class="topic">Evaluation</li>
    </ul>
</div>


</header>


<blockquote class="blockquote">
<p>The previous note ended by asking for a table in which every method gets the same mask. This is that table: five methods, three mask conditions, 151 PIE-Bench images on SD3.5-medium. The background columns shrink to a narrow band, a few differences survive, and the average rank depends on which condition and which columns you read. Along the way, one baseline row in the paper turned out to match what the method’s official script does when it <em>saves</em> an image.</p>
</blockquote>
<p>Paper: Desong Yang and Mang Ye, <em>DirectEdit: Step-Level Accurate Inversion for Flow-Based Image Editing</em>, ICML 2026 — <a href="https://arxiv.org/abs/2605.02417">arXiv:2605.02417</a>. Benchmark: Ju et al., <em>PnPInversion</em> / PIE-Bench — <a href="https://arxiv.org/abs/2310.01506">arXiv:2310.01506</a>. Per-image results, code, figures and review records: <a href="https://github.com/gs3393/pie-bench-equalized-mask">gs3393/pie-bench-equalized-mask</a>.</p>
<section id="where-the-last-note-stopped" class="level2">
<h2 class="anchored" data-anchor-id="where-the-last-note-stopped">Where the last note stopped</h2>
<p>The previous note argued that DirectEdit’s background-preservation score on PIE-Bench does not isolate its inversion contribution, because the method pastes the source latent back outside the edit mask. Holding the mask condition fixed across methods is a necessary control for comparing methods on that column; it is not, by itself, enough to isolate a component, which this note comes back to. I did not have that table. This note is that table.</p>
<p>The scope is the same as before and worth stating before any number: SD3.5-medium at 512², a 151-image subset of PIE-Bench stratified across its ten edit types, one seed per method, and the benchmark’s ground-truth masks. Five methods: FTEdit, FlowEdit, FlowAlign, DNAEdit and DirectEdit — the five SD3.5 methods in DirectEdit’s Table 1, which lists them in six rows because DirectEdit appears with and without its mask. Three conditions each. About 3.5 GPU-hours of generation, counting the two DirectEdit runs carried over from the previous note and excluding evaluation and the auxiliary checks. Per-image results, the runner scripts, the subset ids and the figures are in a <a href="https://github.com/gs3393/pie-bench-equalized-mask">public repository</a>.</p>
</section>
<section id="what-the-same-mask-means-for-five-different-methods" class="level2">
<h2 class="anchored" data-anchor-id="what-the-same-mask-means-for-five-different-methods">What “the same mask” means for five different methods</h2>
<p>Each method carries a different variable through its loop, so “paste the source back” has to be defined per method. The rule I used: after each method’s own update step, replace the carried latent outside the mask with <em>the source trajectory’s latent at the same noise level</em>.</p>
<ul>
<li>DirectEdit, FTEdit and DNAEdit run in noise coordinates and keep a recorded inversion trajectory; they paste the recorded latent for that step.</li>
<li>FlowEdit and FlowAlign carry a clean-coordinate latent that starts at the encoded source and accumulates the edit; they paste the encoded source itself.</li>
</ul>
<p>What this equalizes is the spatial constraint and its preprocessing — the same ground-truth mask, dilated by 3 pixels and downsampled to 64×64 the way DirectEdit’s code does it — not the intervention itself. Three methods restore their own inversion latent, two restore the encoded source, and each decodes through its own VAE path. Restoration is exact only where the processed latent mask is zero; dilation, bilinear downsampling and the decoder’s receptive field mean that pixels just outside the annotation are not copied verbatim. The columns are comparable across rows because every row is scored by the same evaluator on the same annotation, not because the five methods end at an identical background.</p>
<p>The upstream code was not modified; each method’s loop was copied into a runner (DirectEdit’s is imported as-is) with one blending line added — and, because copying five codebases is never that clean, with a handful of other departures from the official scripts (resolution, dtype, a CFG-flag repair in one runner, per-image reseeding in three, the VAE encode mode, the output save path) that the report lists in full. These are adapted runs, not certified reproductions.</p>
<p>Two more conditions bracket the intervention. <strong>No mask</strong> is each method as adapted, with no pasting. <strong>Pixel paste</strong> takes the no-mask output and composites it with the source in pixel space using the same mask the evaluator uses. That last one is not a method; it is a constructed control. Restoring the reference pixels outside the evaluation mask fixes its background scores by construction, and it says nothing about editing quality or how natural the boundary looks.</p>
</section>
<section id="three-conditions-five-methods" class="level2">
<h2 class="anchored" data-anchor-id="three-conditions-five-methods">Three conditions, five methods</h2>
<p>No mask:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Structure ↓</th>
<th>bg-PSNR ↑</th>
<th>bg-LPIPS ↓</th>
<th>bg-MSE ↓</th>
<th>bg-SSIM ↑</th>
<th>CLIP-whole ↑</th>
<th>CLIP-edit ↑</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FTEdit</td>
<td>21.49</td>
<td>23.61</td>
<td>88.07</td>
<td>59.58</td>
<td>87.16</td>
<td>25.14</td>
<td>21.76</td>
</tr>
<tr class="even">
<td>FlowEdit</td>
<td>24.48</td>
<td>22.86</td>
<td>90.80</td>
<td>74.75</td>
<td>85.73</td>
<td><strong>27.52</strong></td>
<td><strong>24.02</strong></td>
</tr>
<tr class="odd">
<td>FlowAlign</td>
<td><strong>13.26</strong></td>
<td><strong>27.32</strong></td>
<td><strong>45.44</strong></td>
<td><strong>26.85</strong></td>
<td><strong>91.30</strong></td>
<td>26.66</td>
<td>22.67</td>
</tr>
<tr class="even">
<td>DNAEdit</td>
<td>14.25</td>
<td>26.48</td>
<td>71.39</td>
<td>33.05</td>
<td>89.91</td>
<td>26.45</td>
<td>22.94</td>
</tr>
<tr class="odd">
<td>DirectEdit</td>
<td>17.22</td>
<td>26.13</td>
<td>68.24</td>
<td>33.82</td>
<td>88.84</td>
<td>26.19</td>
<td>22.53</td>
</tr>
</tbody>
</table>
<p>Everybody pastes the ground-truth mask:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Structure ↓</th>
<th>bg-PSNR ↑</th>
<th>bg-LPIPS ↓</th>
<th>bg-MSE ↓</th>
<th>bg-SSIM ↑</th>
<th>CLIP-whole ↑</th>
<th>CLIP-edit ↑</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FTEdit</td>
<td>9.98</td>
<td>34.85</td>
<td>10.50</td>
<td>5.69</td>
<td><strong>95.06</strong></td>
<td>24.71</td>
<td>21.77</td>
</tr>
<tr class="even">
<td>FlowEdit</td>
<td>14.26</td>
<td>33.58</td>
<td>12.48</td>
<td>6.83</td>
<td>94.57</td>
<td><strong>26.63</strong></td>
<td><strong>23.94</strong></td>
</tr>
<tr class="odd">
<td>FlowAlign</td>
<td>9.03</td>
<td>34.77</td>
<td>10.64</td>
<td>5.71</td>
<td>94.79</td>
<td>26.36</td>
<td>22.96</td>
</tr>
<tr class="even">
<td>DNAEdit</td>
<td><strong>7.72</strong></td>
<td>34.72</td>
<td>10.60</td>
<td>5.72</td>
<td>94.85</td>
<td>25.79</td>
<td>22.80</td>
</tr>
<tr class="odd">
<td>DirectEdit</td>
<td>8.73</td>
<td><strong>35.01</strong></td>
<td><strong>10.16</strong></td>
<td><strong>5.49</strong></td>
<td>94.70</td>
<td>25.42</td>
<td>22.39</td>
</tr>
<tr class="even">
<td>no-edit reference</td>
<td>0.55</td>
<td>35.77</td>
<td>9.28</td>
<td>5.10</td>
<td>94.94</td>
<td>23.47</td>
<td>20.23</td>
</tr>
</tbody>
</table>
<p>What the columns measure matters for everything that follows. Structure Distance is the mean squared difference between DINO self-similarity matrices of the whole source and the whole edited image. The four background metrics zero the annotated edit region in both images and then score the whole frame, so PSNR and MSE keep the whole-frame denominator, which is why their absolute values run high. CLIP-whole scores the target prompt against the whole edited image; CLIP-edit scores it against the edited image with the pixels outside the annotation zeroed — the edited region without its real surround, but including whatever the method left inside the annotation near the boundary. Scales follow the paper’s tables: Structure Distance and LPIPS ×10³, MSE ×10⁴, SSIM ×10². Background columns average the 120 images whose annotation leaves a background; the rest use all 151. The no-edit reference is the source encoded and decoded through DirectEdit’s VAE path, scored by the same script — a reference, not a bound; FTEdit’s SSIM lands above it.</p>
<p>Pixel paste makes every background column identical across the five methods to the last decimal (PSNR infinite, LPIPS and MSE zero, SSIM 99.998), leaves CLIP-edit exactly where the no-mask row had it, and orders Structure Distance as DNAEdit 7.89, FlowAlign 9.22, DirectEdit 9.86, FTEdit 10.44, FlowEdit 14.11.</p>
</section>
<section id="what-compresses-and-what-does-not" class="level2">
<h2 class="anchored" data-anchor-id="what-compresses-and-what-does-not">What compresses, and what does not</h2>
<p>Between the no-mask and GT-mask tables, the spread of mean background PSNR across methods goes from 4.46 dB to 1.43 dB: four methods lie within 0.29 dB of one another, and FlowEdit sits 1.14–1.43 dB below those four. The other three background columns narrow on their own scales — LPIPS from a 45-point spread to 2.3, MSE from 48 to 1.3, SSIM from 5.6 to 0.5. Every method closes between 83% and 102% of its own distance to the no-edit reference on those four columns.</p>
<p>Compression is not erasure. Some pairwise differences survive an image-paired bootstrap: DirectEdit’s background PSNR is 0.29 dB above DNAEdit’s with a 95% interval of [+0.13, +0.46], and it is 1.43 dB above FlowEdit’s. But the same comparison that was +2.52 dB against FTEdit without masks is +0.17 dB with them, interval crossing zero; and the DirectEdit–DNAEdit difference changes sign, from −0.35 dB without masks to +0.29 dB with them. These intervals are exploratory — pointwise, uncorrected for multiplicity, one seed — so read them as “detectable here,” not as settled, and not as a statement about whether the difference is visible.</p>
<p>The three non-background columns keep between-method variation, and they shrink less, proportionally, than the four background columns: the spread across methods falls by about 42% for Structure Distance (11.2 to 6.5), about 19% for CLIP-whole (2.38 to 1.92), and about 4% for CLIP-edit (2.26 to 2.17). Differences on these columns are not comparable in size with one another or with the background columns. Averaged across all 151 images, pasting the mask changes CLIP-edit by between −0.15 (DNAEdit) and +0.29 (FlowAlign); individual images can lose five or six points, so this is a statement about means. Figure 1 is the largest single CLIP-edit decrease in the set, from 21.1 to 15.0, between FlowAlign runs without and with per-step blending. The two are separate generations, not one edit clipped by a mask: the masked run keeps more of the toy and renders the cloud differently. Which of those changes moved the score, the comparison does not isolate — CLIP-edit sees only the pixels inside the annotation in both conditions.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/equalized-mask-table/fig1-clip-drop.png" class="img-fluid figure-img" alt="Four panels: a toy figure on a table; the same image with the table region tinted red; FlowAlign's edit placing the toy on a cloud without mask blending; the edit with mask blending, where more of the toy is preserved and the cloud is rendered differently."></p>
<figcaption>Figure 1. Source, ground-truth mask, and FlowAlign without and with per-step GT-mask blending. CLIP-edit falls from 21.1 to 15.0; the two right-hand panels are separate generation conditions, not a pixel crop of one edit.</figcaption>
</figure>
</div>
<p>Pasting also does things the averages hide. Figure 2 is a case where Structure Distance rose after the paste, from 7.9 to 12.2, while background PSNR reached 38.3 dB. The masked run preserves the figurine, which the unmasked run had distorted, but renders the cucumber differently, with a straight edge near the mask boundary. Which change drives the higher Structure Distance, the panels do not say. Structure Distance is not an editing-success score either: the no-edit reference — a VAE round-trip of the source, no edit at all — has the lowest mean of any condition, 0.55.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/equalized-mask-table/fig2-seam.png" class="img-fluid figure-img" alt="Three panels: a figurine on a white table with the table region tinted red; FlowAlign's unmasked edit adding a cucumber and distorting the figurine; the masked edit preserving the figurine with a differently rendered cucumber and a straight edge near the mask boundary."></p>
<figcaption>Figure 2. FlowAlign without and with per-step GT-mask blending on an edit that adds a cucumber. Structure Distance 7.9 → 12.2; background PSNR 38.3 dB in the masked run.</figcaption>
</figure>
</div>
</section>
<section id="the-ranking-depends-on-which-table-you-read" class="level2">
<h2 class="anchored" data-anchor-id="the-ranking-depends-on-which-table-you-read">The ranking depends on which table you read</h2>
<p>DirectEdit’s Table 1 summarizes each method with an average of its per-metric ranks. With ties averaged, here is how the five methods order under each condition, alongside the paper’s own SD3.5 rows for these five methods ranked the same way (its no-mask DirectEdit row left out):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Table</th>
<th>1st</th>
<th>2nd</th>
<th>3rd</th>
<th>4th</th>
<th>5th</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Paper, Table 1 SD3.5 rows for the five methods (only DirectEdit masked)</td>
<td>DirectEdit 1.50</td>
<td>DNAEdit 2.57</td>
<td>FlowAlign 3.21</td>
<td>FlowEdit 3.71</td>
<td>FTEdit 4.00</td>
</tr>
<tr class="even">
<td>Nobody pastes</td>
<td>FlowAlign 1.43</td>
<td>DNAEdit 2.29</td>
<td>DirectEdit 3.14</td>
<td>FlowEdit 3.86</td>
<td>FTEdit 4.29</td>
</tr>
<tr class="odd">
<td>Everybody pastes the GT mask</td>
<td>DirectEdit 2.43</td>
<td>FlowAlign · DNAEdit 2.86</td>
<td>—</td>
<td>FTEdit 3.00</td>
<td>FlowEdit 3.86</td>
</tr>
<tr class="even">
<td>GT mask, background columns removed</td>
<td>FlowAlign · DNAEdit · FlowEdit 2.33</td>
<td>—</td>
<td>—</td>
<td>DirectEdit 3.33</td>
<td>FTEdit 4.67</td>
</tr>
<tr class="odd">
<td>Pixel paste</td>
<td>DNAEdit 2.57</td>
<td>FlowEdit · FlowAlign 2.71</td>
<td>—</td>
<td>DirectEdit 3.29</td>
<td>FTEdit 3.71</td>
</tr>
</tbody>
</table>
<p>On this subset DirectEdit ranks third without masking and first under GT-mask blending, 0.43 mean-rank points ahead of the tied runners-up. It ranks fourth when the four background metrics are left out of the GT-mask ranking, and fourth again in the separate pixel-compositing condition — which changes the evaluated images, Structure and CLIP-whole included, as well as tying the background columns. That is a statement about sensitivity: the order depends on the mask condition and on how much weight the background columns carry. It is not a finding about <em>why</em> the paper’s table orders the way it does — the paper used 700 images, MLLM-derived masks and the authors’ own runs, and this experiment does not reproduce that setup. The earlier draft of this note said more than that, and an external audit made me take it back.</p>
</section>
<section id="what-the-alignment-buys-as-far-as-this-table-can-say" class="level2">
<h2 class="anchored" data-anchor-id="what-the-alignment-buys-as-far-as-this-table-can-say">What the alignment buys, as far as this table can say</h2>
<p>The honest answer is that this table cannot isolate it. FTEdit is DirectEdit’s code ancestor and the natural comparison, but it is not “DirectEdit minus alignment”: the two differ in inversion scheme, in the AdaLN and attention injection ratios, in how the source branch is guided. With the mask equalized, DirectEdit’s LPIPS, MSE and CLIP-edit are better than FTEdit’s by amounts whose intervals exclude zero (−0.34, −0.20 and +0.62 on the paper’s scales), its PSNR is not distinguishable (+0.17 dB), and its SSIM is worse (−0.35). Its mean background PSNR is 0.29 dB above DNAEdit’s and 0.24 dB above FlowAlign’s — the second interval includes zero — and its CLIP scores are below both. The comparison with FlowEdit runs the same way, only larger: +1.43 dB of PSNR, −1.55 points of CLIP-edit. These are comparisons between configured systems. Attributing any of them to alignment would take a component ablation in this SD3.5 setup with everything else held fixed; the paper’s FLUX ablation illustrates that design but does not estimate these differences.</p>
</section>
<section id="one-baseline-row-that-does-not-look-like-the-method" class="level2">
<h2 class="anchored" data-anchor-id="one-baseline-row-that-does-not-look-like-the-method">One baseline row that does not look like the method</h2>
<p>While building the no-mask table, agreement with the paper’s SD3.5 rows varied by method and by metric: FTEdit and DirectEdit were close on most columns, DNAEdit and FlowEdit were off by more on some. FlowAlign stood out. The paper reports Structure 33.49 and background PSNR 24.06 for it — a Structure Distance worse than FlowEdit’s 23.13, which is odd for a method whose own paper claims better preservation than FlowEdit. Running FlowAlign’s released code on my subset gave 13.26 and 27.32, the best no-mask preservation of the five.</p>
<p>The largest single factor I found is how the official script <em>saves</em> its output. <code>run_edit.py</code> writes the result with torchvision’s <code>save_image(..., normalize=True)</code>, which, absent an explicit range, rescales each image by its own minimum and maximum. That is a fine default for looking at pictures and a bad one for feeding PNGs to a PSNR evaluator: it changes the saved pixels, inside and outside the edit, while leaving the generation itself untouched. I re-ran the same 151 inputs with the same seeds and settings, changing only the runner’s output conversion to per-image min/max — the policy FlowAlign’s script selects; byte-for-byte equivalence to its saver was not tested — and scored the result:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>FlowAlign, 151 images</th>
<th>Structure ↓</th>
<th>bg-PSNR ↑</th>
<th>bg-LPIPS ↓</th>
<th>bg-MSE ↓</th>
<th>bg-SSIM ↑</th>
<th>CLIP-whole ↑</th>
<th>CLIP-edit ↑</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>saved with a fixed [−1, 1] range</td>
<td>13.26</td>
<td>27.32</td>
<td>45.44</td>
<td>26.85</td>
<td>91.30</td>
<td>26.66</td>
<td>22.67</td>
</tr>
<tr class="even">
<td>saved with per-image min/max, as the official script does</td>
<td>36.11</td>
<td>24.81</td>
<td>53.39</td>
<td>45.66</td>
<td>88.47</td>
<td>26.60</td>
<td>22.59</td>
</tr>
<tr class="odd">
<td>the paper’s row (700 images)</td>
<td>33.49</td>
<td>24.06</td>
<td>68.91</td>
<td>54.29</td>
<td>86.33</td>
<td>25.64</td>
<td>22.40</td>
</tr>
</tbody>
</table>
<p>Structure Distance rises from 13.3 to 36.1 against the paper’s 33.5; PSNR falls from 27.3 to 24.8 dB against 24.1; SSIM from 91.3 to 88.5 against 86.3. MSE moves about two thirds of the way toward the paper’s value and LPIPS about a third. The CLIP scores move a little — CLIP-whole from 26.66 to 26.60 and CLIP-edit from 22.67 to 22.59 on average, with individual images moving by up to about three points either way — because the saved pixels inside the edit change too. Figure 3 shows the effect on one image: the black background becomes dark grey and the mouse gets brighter, and background PSNR drops from 32.7 to 17.6 dB for an identical generation.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/equalized-mask-table/fig3-flowalign-save.png" class="img-fluid figure-img" alt="Three panels: a white mouse on a black background; FlowAlign's purple-mouse edit saved with a fixed range, black background preserved; the same edit saved with per-image min/max normalization, background turned dark grey and the mouse brighter."></p>
<figcaption>Figure 3. One FlowAlign generation converted two ways. Left: source. Middle: saved with a fixed range. Right: saved with per-image min/max normalization, the policy the official script selects.</figcaption>
</figure>
</div>
<p>In a 20-image check, generating at the script’s default 1024² and downsampling before scoring did not reproduce the paper’s means under either save mode; that does not rule out resolution effects in the authors’ setup. I have not seen the authors’ evaluation code and cannot say what they ran. What this establishes is that, in these adapted runs, the output normalization alone moves the preservation metrics a long way, and that several of the resulting means end up close to the paper’s row while others stay well off it. Whether the paper’s row was produced this way is unverified. If it was, it is an easy trap: “official recommended settings” includes the line that writes the file.</p>
<p>What I can state from this experiment alone is narrower. Holding the other four methods fixed and re-scoring only FlowAlign’s outputs converted the two ways, FlowAlign is third in the five-method no-mask ranking when saved with per-image min/max (mean rank 2.86, behind DNAEdit at 1.71 and DirectEdit at 2.57) and first when saved with a fixed range (1.43). The save path alone moves it two places in my table.</p>
<p>Two corrections to my own process belong here. My first attempt at the 1024² check saved the larger canvas as-is and let the evaluator crop its bottom-right 512² — a quarter of the edited image scored against the whole source — and I had written it up as a collapse before an adversarial review of the report caught it. And the 20-image pilot of the save-path test had a Structure Distance of 75, which looked like a mismatch until the full 151 images gave 36; the two sets differ in composition as well as size, so I do not know which of the two accounts for it.</p>
</section>
<section id="how-to-read-a-table-like-this" class="level2">
<h2 class="anchored" data-anchor-id="how-to-read-a-table-like-this">How to read a table like this</h2>
<p>The previous note asked for a no-edit reference row and for the mask condition to be held fixed when reading background columns as evidence about an algorithm. What this table adds:</p>
<ul>
<li>After masking, the background columns are a narrow band: four methods within 0.29 dB of PSNR, FlowEdit 1.1–1.4 dB below them. Whether differences of that size matter is a question about the use case, and the table cannot answer it. What the table can say is that an average over four such columns gives them four sevenths of the weight, so small differences there move the rank.</li>
<li>The three non-background columns keep between-method variation, but none of them is a score for having edited well. Structure Distance is a whole-image similarity that the no-edit reference wins on average; CLIP-edit scores the target text against the edited region without its real surround; CLIP-whole mixes the two.</li>
<li>“Official settings” reach all the way to the file writer. Before scoring a baseline’s PNGs, check that they are the pixels the method produced. In my five-method no-mask table, changing FlowAlign’s output normalization changes its rank from first to third, and it would have done so unnoticed if I had used the official script’s saver.</li>
</ul>
<p>Put in one sentence: in this setup, restoring the source through the same ground-truth mask shrank the between-method gaps on the background metrics substantially; some differences remained; and the average rank was sensitive to the mask condition and to which metrics were averaged. The comparison does not identify the effect of DirectEdit’s alignment on its own, nor the cause of the ranking in the paper.</p>
</section>
<section id="limits" class="level2">
<h2 class="anchored" data-anchor-id="limits">Limits</h2>
<ul>
<li>151 images, one seed per method, SD3.5-medium, ground-truth masks. No automatic-mask condition was run with masks equalized, so this is an intervention experiment, not a leaderboard for image-plus-text systems.</li>
<li>The five baseline runs are adapted, not official; the departures are listed in the report.</li>
<li>The paired intervals are pointwise image bootstraps without seed replication or multiplicity correction. An interval that excludes zero says the difference is detectable on these images; it does not say it is visible or stable across seeds. An interval that includes zero does not say the methods are equal.</li>
<li>The no-edit reference is one VAE path (DirectEdit’s); FTEdit and FlowAlign decode through their own, so the five methods do not end at a numerically identical reference image.</li>
<li>The FlowAlign result establishes a save-path effect in my runs; it does not establish which script the authors ran.</li>
<li>An earlier version of the measurement report was audited adversarially by a second model; that audit found the first 1024² check mis-scored and several overstatements, which were corrected. This note then went through a further interpretation-level review by the same kind of reviewer, whose findings are applied here. The audit records, the data and the code are in the <a href="https://github.com/gs3393/pie-bench-equalized-mask">public repository</a>.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/gs3393\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 gs3393</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://github.com/gs3393">
<p>GitHub</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>