<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-06">
<meta name="description" content="The core idea behind FD-loss, the disagreement between FID and FDr6 in JiT, and what these results reveal about possible causes.">

<title>When FID Becomes the Loss: Reading JiT’s One-Step Results – gs3393</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-172ba59bd5e0b52282274ba0c0cc16fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">gs3393</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">
<span class="menu-text">Home</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../work.html">
<span class="menu-text">Work</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../notes.html">
<span class="menu-text">Notes</span></a>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/gs3393"> <i class="bi bi-github" role="img">
</i>
<span class="menu-text"></span></a>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>

  <ul class="collapse">
  <li><a href="#the-idea-and-contributions-of-fd-loss" id="toc-the-idea-and-contributions-of-fd-loss" class="nav-link active" data-scroll-target="#the-idea-and-contributions-of-fd-loss">The idea and contributions of FD-loss</a></li>
  <li><a href="#where-jits-evaluation-scores-disagree" id="toc-where-jits-evaluation-scores-disagree" class="nav-link" data-scroll-target="#where-jits-evaluation-scores-disagree">Where JiT’s evaluation scores disagree</a></li>
  <li><a href="#what-the-average-conceals" id="toc-what-the-average-conceals" class="nav-link" data-scroll-target="#what-the-average-conceals">What the average conceals</a></li>
  <li><a href="#could-the-starting-model-matter" id="toc-could-the-starting-model-matter" class="nav-link" data-scroll-target="#could-the-starting-model-matter">Could the starting model matter?</a></li>
  <li><a href="#what-remains-unexplained" id="toc-what-remains-unexplained" class="nav-link" data-scroll-target="#what-remains-unexplained">What remains unexplained</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">When FID Becomes the Loss: Reading JiT’s One-Step Results</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Analysis</div>
    <div class="quarto-category">Generative Models</div>
    <div class="quarto-category">Evaluation</div>
  </div>
  </div>

<div>
  <div class="description">
    The core idea behind FD-loss, the disagreement between FID and FDr6 in JiT, and what these results reveal about possible causes.
  </div>
</div>


<div class="quarto-title-meta">


    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 6, 2026</p>
    </div>
  </div>


  </div>



</header>


<blockquote class="blockquote">
<p>Converting JiT into a one-step generator with FD-Inception improves FID but worsens FDr6 relative to its original 50-step results. This note examines what that disagreement shows and what it leaves unexplained.</p>
</blockquote>
<section id="the-idea-and-contributions-of-fd-loss" class="level2">
<h2 class="anchored" data-anchor-id="the-idea-and-contributions-of-fd-loss">The idea and contributions of FD-loss</h2>
<p><em>Representation Fréchet Loss for Visual Generation</em> uses Fréchet distance (FD), an image evaluation measure, as a loss for post-training generators. A pretrained representation model extracts features from real and generated images, and the generator is updated to bring their feature means and covariances closer. With Inception features, this distance becomes the familiar <strong>FID</strong> metric. <a href="https://arxiv.org/html/2604.28190v1#S3.SS1">FD-Loss, §3.1</a>.</p>
<p>The key idea is to <strong>separate the population size used for distribution estimation from the batch size used for backpropagation</strong>. Features or their statistics accumulate across batches, while gradients flow only through the current batch. This makes matching distributions over a large sample population computationally manageable. <a href="https://arxiv.org/html/2604.28190v1#S3.SS2">FD-Loss, §3.2</a>.</p>
<p>The paper shows that this approach can improve existing one-step generators and convert multi-step models into one-step generators without per-sample teacher predictions. It also shows that FID and other evaluations can disagree depending on the training representation, and introduces <strong>FDr6</strong> to aggregate distances across several representations. <a href="https://arxiv.org/html/2604.28190v1#S3.SS3">FD-Loss, §§3.3–4</a>.</p>
</section>
<section id="where-jits-evaluation-scores-disagree" class="level2">
<h2 class="anchored" data-anchor-id="where-jits-evaluation-scores-disagree">Where JiT’s evaluation scores disagree</h2>
<p>JiT normally generates images through repeated denoising. Post-training with FD-loss enables generation in a single network call, but <strong>the evaluation of that result depends on the representation used for training</strong>. The main comparison here is between <strong>FD-Inception</strong>, which uses Inception alone, and <strong>FD-SIM</strong>, which combines SigLIP, Inception, and MAE.</p>
<p>FDr6 averages normalized FD values across six spaces: Inception, ConvNeXt, DINOv2, MAE, SigLIP, and CLIP. In each space, generated-to-training distance is divided by validation-to-training distance. Both FID and FDr6 are better when lower. FDr6 complements evaluation in a single representation, but it does not directly measure human preference. <a href="https://arxiv.org/html/2604.28190v1#S3.SS4">FD-Loss, §3.4</a>.</p>
<p>The following results use JiT-L/16 on ImageNet 256 × 256. The post-trained models receive 50 epochs of additional training, and evaluation uses 50,000 generated images. <a href="https://arxiv.org/html/2604.28190v1#S4.T2">FD-Loss, Table 2 and §4</a>.</p>
<div id="tbl-jit-results" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-jit-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: JiT-L results reported in FD-Loss Table 2. The 50-step reference uses 200 network evaluations: 50 steps × 2 for the Heun solver × 2 for classifier-free guidance. Each one-step condition uses one network evaluation.
</figcaption>
<div aria-describedby="tbl-jit-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Generator / post-training loss</th>
<th style="text-align: left;">Generation</th>
<th style="text-align: right;">FID ↓</th>
<th style="text-align: right;">FDr6 ↓</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Original JiT-L</td>
<td style="text-align: left;">50-step</td>
<td style="text-align: right;">2.59</td>
<td style="text-align: right;">10.73</td>
</tr>
<tr class="even">
<td style="text-align: left;">Original JiT-L</td>
<td style="text-align: left;">One-step</td>
<td style="text-align: right;">291.59</td>
<td style="text-align: right;">214.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FD-Inception</td>
<td style="text-align: left;">One-step</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">12.86</td>
</tr>
<tr class="even">
<td style="text-align: left;">FD-MAE</td>
<td style="text-align: left;">One-step</td>
<td style="text-align: right;">6.52</td>
<td style="text-align: right;">9.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FD-SigLIP</td>
<td style="text-align: left;">One-step</td>
<td style="text-align: right;">5.10</td>
<td style="text-align: right;">9.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">FD-SigLIP + MAE</td>
<td style="text-align: left;">One-step</td>
<td style="text-align: right;">4.67</td>
<td style="text-align: right;">3.83</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FD-SIM</td>
<td style="text-align: left;">One-step</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">3.29</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The first two rows show why conversion training is needed. Simply calling the original model once produces very poor scores. FD-Inception makes a large improvement from this starting point: FID falls from 291.59 to 0.77, and FDr6 from 214.75 to 12.86.</p>
<p>The disagreement appears when comparing against <strong>the original model running its full 50-step sampler</strong>. FD-Inception has a better FID but a worse FDr6. FD-SIM has a slightly higher FID than FD-Inception and a much lower FDr6. Selecting a model by FID alone would therefore favor a different result than selecting by the broader evaluation panel.</p>
<p>Another detail matters: MAE or SigLIP alone also yields a lower FDr6 than the 50-step reference. The table does not support a simple explanation that conversion is impossible with a single representation. Which representation is used, and what information it supplies for this conversion, matters.</p>
<p>The comparison baseline needs care. The 50-step reference is a different sampling procedure, not an earlier point on the one-step training curve. Finishing with a higher FDr6 than that reference does not establish that training destroyed performance the one-step generator previously had. Some properties of the multi-step result may never have been sufficiently recovered in one step.</p>
</section>
<section id="what-the-average-conceals" class="level2">
<h2 class="anchored" data-anchor-id="what-the-average-conceals">What the average conceals</h2>
<div id="fig-representation-fdr" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Per-representation FDr for the original 50-step JiT-L, FD-Inception, and FD-SIM. FD-Inception has higher DINOv2, MAE, and SigLIP distances than the 50-step reference; FD-SIM has lower distances in all six spaces.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-representation-fdr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/jit-fd-loss/representation-fdr.svg" class="img-fluid figure-img" alt="Per-representation FDr for the original 50-step JiT-L, FD-Inception, and FD-SIM. FD-Inception has higher DINOv2, MAE, and SigLIP distances than the 50-step reference; FD-SIM has lower distances in all six spaces." width="780">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-representation-fdr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Final results in six representation spaces. Lower is better. Replotted from FD-Loss Table F.4; lines connect corresponding endpoints, not intermediate training states.
</figcaption>
</figure>
</div>
<p>The per-representation comparison in <a href="#fig-representation-fdr" class="quarto-xref">Figure&nbsp;1</a> shows that FD-Inception’s worse average does not mean uniform deterioration. Relative to the 50-step reference, DINOv2, MAE, and SigLIP distances increase, while Inception, ConvNeXt, and CLIP distances decrease. The particularly large gaps in MAE and SigLIP make the disagreement clearer than the aggregate alone.</p>
<p>Three of FDr6’s six representations also appear in SIM’s training loss, so an improved aggregate score alone cannot establish improvement outside the training representations. Here, SIM lowers all six distances, including ConvNeXt, DINOv2, and CLIP, which are outside its training set of representations. This is evidence of improvement beyond the spaces directly optimized, although those additional evaluators do not cover every visual property.</p>
<p>These results make the observation more specific. Inception optimization produces a generator that matches one set of feature statistics especially well, with uneven improvement elsewhere. Calling this “metric gaming” can express the concern without explaining its cause. An increase in MAE distance also cannot be translated directly into a loss of a particular property, such as shape or texture. The metric comparison needs to be read alongside the paper’s visual evidence.</p>
<p>The paper’s <a href="https://arxiv.org/html/2604.28190v1#S4.F5">Figure 5</a> places outputs from the original JiT and models post-trained with different losses side by side, using the same noise inputs. In the dog example, the original one-step model’s blurry output becomes a recognizable dog after post-training, while Inception and SIM also differ in background and texture. These examples provide evidence of changes visible in the images themselves. A small set of examples cannot establish which condition people prefer more often, how consistently the differences occur across the generated distribution, or what causes them.</p>
<p>There is also evidence about human preference. In the base-model comparison in <a href="https://arxiv.org/html/2604.28190v1#S4.F6">Figure 6</a>, models post-trained with FD-SIM are preferred. However, this evaluates <strong>FD-SIM against the corresponding base models</strong>; it does not directly test the Inception–SIM difference in JiT.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Exact values and figure source">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exact values and figure source
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Representation</th>
<th style="text-align: right;">Original 50-step</th>
<th style="text-align: right;">FD-Inception</th>
<th style="text-align: right;">FD-SIM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Inception</td>
<td style="text-align: right;">1.54</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.51</td>
</tr>
<tr class="even">
<td style="text-align: left;">ConvNeXt</td>
<td style="text-align: right;">3.49</td>
<td style="text-align: right;">2.57</td>
<td style="text-align: right;">1.09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DINOv2</td>
<td style="text-align: right;">6.10</td>
<td style="text-align: right;">7.34</td>
<td style="text-align: right;">3.06</td>
</tr>
<tr class="even">
<td style="text-align: left;">MAE</td>
<td style="text-align: right;">8.07</td>
<td style="text-align: right;">15.28</td>
<td style="text-align: right;">1.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SigLIP</td>
<td style="text-align: right;">19.37</td>
<td style="text-align: right;">26.22</td>
<td style="text-align: right;">2.78</td>
</tr>
<tr class="even">
<td style="text-align: left;">CLIP</td>
<td style="text-align: right;">25.82</td>
<td style="text-align: right;">25.29</td>
<td style="text-align: right;">11.30</td>
</tr>
</tbody>
</table>
<p>Source: <a href="https://arxiv.org/html/2604.28190v1#A6.T4">FD-Loss v1, Table F.4</a>. The paper uses SigLIP2 and labels it SigLIP in the tables; the figure preserves that label. Download the <a href="assets/jit-fd-loss/table-f4.csv">transcribed CSV</a> and <a href="assets/jit-fd-loss/plot-fdr.py">plotting script</a>.</p>
</div>
</div>
</div>
</section>
<section id="could-the-starting-model-matter" class="level2">
<h2 class="anchored" data-anchor-id="could-the-starting-model-matter">Could the starting model matter?</h2>
<p>FD-Loss also post-trains pMF and iMF, which already generate in one step. In its separate 100-epoch comparison, Inception post-training improves their FDr6, while JiT remains worse than its original multi-step reference on that metric. <a href="https://arxiv.org/html/2604.28190v1#S4.T3">FD-Loss, Table 3</a>.</p>
<p>This contrast connects to the authors’ suggestion that converting a denoiser is harder than improving an existing one-step generator. <a href="https://arxiv.org/html/2604.28190v1#S4.SS3">FD-Loss, §4.3</a>. In multi-step generation, an intermediate prediction is used to update the current sample; in one-step generation, a single output must be the final image. A representation that supplies useful corrections to a function already producing complete samples may be insufficient to teach a denoiser to perform the entire process in one call.</p>
<p>That explanation is plausible, but the comparison changes more than the starting ability. The model families differ in architecture and training history, and JiT uses a different post-training learning rate. Their results cannot isolate conversion difficulty as the cause. What they show is that the same loss can behave differently across settings.</p>
<p>The remaining question is therefore: <strong>does Inception fail to teach some properties needed for conversion, or can optimizing it also undo those properties once they are present?</strong></p>
</section>
<section id="what-remains-unexplained" class="level2">
<h2 class="anchored" data-anchor-id="what-remains-unexplained">What remains unexplained</h2>
<p>The first possibility is an incomplete learning signal. Inception statistics may become easy to match before the generator learns everything needed to satisfy the other representations. In this case, the gap concerns what conversion has yet to achieve.</p>
<p>The second possibility is a conflict between objectives. A change that brings Inception features closer to the real-data reference can move another representation’s features farther away. Reducing distance in one space provides no mathematical guarantee of improvement in another. This could also affect a generator that already produces good one-step samples.</p>
<p>Optimization offers another explanation. The paper normalizes each FD term, but this does not equalize the magnitudes and directions of parameter gradients. Differences in the actual updates induced by the losses therefore remain a possible explanation. <a href="https://arxiv.org/html/2604.28190v1#S3.SS2">FD-Loss, §3.2 and Eq. 6</a>. Accumulated feature statistics may also reflect earlier generator states. These training dynamics could partly account for a difference attributed to the representation. The published endpoints do not distinguish these explanations, and identifying which metric improved does not establish the cause.</p>
<p>A useful follow-up would compare Inception refinement from an already good one-step JiT with conversion from the original denoiser. With continued SIM training as a control, learning curves could help distinguish distances that never recover from distances that improve and later reverse. This is the kind of evidence missing from the current tables.</p>
<p>The central lesson for reading the paper is concrete. FD-loss gives a representation model a role in both evaluating and teaching the generator. JiT shows why those roles deserve separate scrutiny. Success in the training representation need not translate into even improvement elsewhere, and the learning signal required of that representation changes when the generator must learn a new way to produce images.</p>
<hr>
<p><em>Source scope:</em> This note analyzes the JiT results reported in FD-Loss <code>2604.28190v1</code>. All numerical results come from the paper, and the figure replots those values. The possible causes discussed here are interpretations, not findings established by new experiments.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button,
          { trigger: "manual",
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined;
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              }
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            }
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>
